baseURL = 'https://maximeneuville.archi/'
defaultContentLanguage = "fr"
languageCode = 'fr-FR'
title = 'Maxime Neuville'

[params]
  subtitle = "Architecte"
  description = ""
  keywords = []
  display_breabcrumbs = true
  [params.author]
    image = "img/author.jpg"
    name = 'Maxime Neuville'
    suffix = 'Architecte'
    # headline = "Une petite phrase d'accroche ou citation"
    address = "2 cité de la boule d'Or 12 000 RODEZ"
    phone = '+ 33 (0)6 32 17 39 42'
    email = 'neuville.maxime@outlook.fr'
    bio = "Inscrit à l'Ordre des Architectes Occitanie n°089902 - EI - Entrepreneur Individuel"
    links = [
      { instagram = "#" },
      { facebook = "https://facebook.com/" },
      { linkedin = "https://linkedin.com/" },
      { x-twitter = "https://twitter.com/" },
      { youtube = "https://youtube.com/" },
    ]
  [[params.social]]
    name = "instagram"
    url = ""

[menu]
  [[menu.main]]
    identifier = "projets"
    name = "Projets"
    url = "/projets"
    weight = 10
  [[menu.main]]
    identifier = "a-propos"
    name = "À propos"
    url = "/a-propos"
    weight = 20
  [[menu.main]]
    identifier = "noues"
    name = "Nou(e)s"
    url = "/noues"
    weight = 30