baseURL = "https://example.com/"
title = "MAXIME NEUVILLE"
copyright =  "Inscrit à l’Ordre des Architectes Occitanie n°089902 - EI - Entrepreneur Individuel"
defaultContentLanguage = "fr"
languageCode = "fr-FR"
theme = ["gohugo-theme-subre"]

[author]
    name = "Maxime Neuville"
    suffix = "Architecte"
    email = "neuville.maxime@outlook.fr"
    phone = "+ 33 (0)6 32 17 39 42"
    address = "2 cité de la boule d’Or 12 000 RODEZ"
#    bio = ""
    image = "/images/home.jpg"

[noues]
    name = "Nou(e)s"
    suffix = "Architecte"
    email = "neuville.maxime@outlook.fr"
    phone = "+ 33 (0)6 32 17 39 42"
    address = "2 cité de la boule d’Or 12 000 RODEZ"
#    bio = ""
    image = "/images/noues.jpg"

[params]
  subtitle = "Architecte"
  description = ""
  keywords = []
#  [[params.social]]
#    name = "instagram"
#    url = ""

[menu]
  [[menu.main]]
    identifier = "projet"
    name = "Projets"
    url = "/projet"
    weight = 10
  [[menu.main]]
    identifier = "a-propos"
    name = "À propos"
    url = "/a-propos"
    weight = 20
  [[menu.main]]
    identifier = "noues"
    name = "Nou(e)s"
    url = "/noues"
    weight = 30
